from pydantic import BaseModel, Field, validator

class GeneratedJavaCode(BaseModel):
    code: str = Field(description="Java code generated by Business Logic")

    @validator('code')
    def validate_java_code(cls, value):
        # Perform custom validation logic here to check if the Java code is valid
        # For example, you can use an external library to check the syntax or do a simple check
        if 'class' not in value:
            raise ValueError("Invalid Java code. It should contain at least one class definition.")
        return value