# Generated by Django 4.2.1 on 2023-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBridge_Backend', '0002_alter_fileupload_user_alter_folderupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='filename',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='folderupload',
            name='foldername',
            field=models.CharField(max_length=2048),
        ),
    ]
