# Generated by Django 4.1.10 on 2023-09-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBridge_Backend', '0008_clonedrepository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clonedrepository',
            name='user',
        ),
        migrations.AddField(
            model_name='clonedrepository',
            name='folder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.folderupload'),
        ),
        migrations.AddField(
            model_name='clonedrepository',
            name='users',
            field=models.ManyToManyField(to='CodeBridge_Backend.user'),
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=256)),
                ('repository_url', models.URLField()),
                ('branch', models.CharField(max_length=256)),
                ('commit_sha', models.CharField(blank=True, max_length=64, null=True)),
                ('collaborators', models.ManyToManyField(related_name='collaborating_repositories', to='CodeBridge_Backend.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.user')),
                ('source_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.folderupload')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.githubrepository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.user')),
            ],
        ),
    ]
