# Generated by Django 4.1.10 on 2023-09-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBridge_Backend', '0012_fileupload_rootfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='javacode',
            name='language_converted',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='javacode',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.githubrepository'),
        ),
    ]
