# Generated by Django 4.2.1 on 2023-06-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FolderUpload',
            fields=[
                ('folderId', models.AutoField(primary_key=True, serialize=False)),
                ('foldername', models.CharField(max_length=1024)),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.folderupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('filename', models.CharField(max_length=1024)),
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.folderupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.user')),
            ],
        ),
    ]
