# Generated by Django 4.2.1 on 2023-06-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBridge_Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.user'),
        ),
        migrations.AlterField(
            model_name='folderupload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.user'),
        ),
    ]
