# Generated by Django 4.2.1 on 2023-06-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBridge_Backend', '0003_alter_fileupload_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic', models.TextField()),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.fileupload')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='JavaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.fileupload')),
                ('logic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.logic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.user')),
            ],
        ),
    ]
