# Generated by Django 4.1.10 on 2023-09-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBridge_Backend', '0009_remove_clonedrepository_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='owner',
            field=models.CharField(max_length=256),
        ),
    ]
