# Generated by Django 4.1.10 on 2023-09-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeBridge_Backend', '0010_alter_githubrepository_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='source_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeBridge_Backend.folderupload'),
        ),
    ]
